### ISSUE TITLE
TODO: dependency upgrade

### ISSUE THREAD

**Issue by patrick-werner** [gematik/api-vzd#118]
- [ ] gerade wird eine neue Version der basisprofile ballotiert, hier sollte die dependency geupdated werden. Entweder jetzt auf die ballot Version: de.basisprofil.r4 1.5.0-ballot, oder nach dem Ballot auf die 1.5.0, oder jetzt ballotversion, und sobald verfügbar update auf die finale Version.
Timeline: Ende März für die finale Version
- [ ]  In der 1.5.0 basisprofile Version wurden die IHE VS und CS entfernt, diese werden in den nächsten Wochen als eigenes package released und muss als dependency hinzugefügt werden.

**Comment by gem-uhe** [comment]
dependency updated
