### ISSUE TITLE
Possibly redundant CodeSystems

### ISSUE THREAD

**Issue by spilikin** [gematik/api-vzd#56]
@SvenSommer 

Two following CodeSystems seem to be redundant. Can you please check?

https://github.com/gematik/api-vzd/blob/main/src/fhir/input/fsh/codesystems/PharmacyTypeCS.fsh

https://github.com/gematik/api-vzd/blob/main/src/fhir/input/fsh/codesystems/PharmacyHealthcareServiceTypeCS.fsh

Its would also be great if you can provide a Sample for Pharmacy-Bundle

**Comment by florianschoffke** [comment]
Perhaps the naming could be improved, but the content is different:
* PharmacyTypeCS describes the kind of pharmacy
* PharmacyHealthcareServiceTypeCS describes what kind of services a pharmacy offers

**Comment by spilikin** [comment]
Ah, thanks! 

BTW: the Codesystems are not bound to Organisation and HealthcareService Profiles. If you expect them to be in central Directory, the CodeSystems must be declared in corresponding ValueSets:
https://github.com/gematik/api-vzd/blob/main/src/fhir/input/fsh/valuesets/OrganizationTypeVS.fsh
https://github.com/gematik/api-vzd/blob/main/src/fhir/input/fsh/valuesets/HealthcareServiceSpecialtyVS.fsh
Do you really need standalone ValueSets?

.. or somehoc declared as Slice (would like to do it that way tbh).

We now have 3 different ways to set the type for Pharmacies:
Specialty:

* urn:oid:1.3.6.1.4.1.19376.3.276.1.5.5#PHZ "Pharmazeutik"

ProfessionOID:

* #1.2.276.0.76.4.54 "Öffentliche Apotheke"
* #1.2.276.0.76.4.55 "Krankenhausapotheke"
* #1.2.276.0.76.4.56 "Bundeswehrapotheke"

Pharmacy Type:
* #10 "Offizin-Apotheke"
* #20 "Krankenhausversorgende Apotheke"
* #30 "Heimversorgende Apotheke"
* #40 "Versandapotheke"

**Comment by florianschoffke** [comment]
Sorry for the late response. 
Do I understand you correctly, that you are asking to also create ValueSets for the given CodeSystems? 

And would you suggest to replace PharmacyType with ProfessionOID?

**Comment by spilikin** [comment]
We will reference the additional CodeSystems in existing ValueSets, I just wanted to let you know it's not the case yet.

Same with ProfessionOID - those are very restrictive and hard to extend, since they are part of X.509 PKI. 

I am just a litte bit concerned about the implementers - we must give them the clear Implementation Guide which Codes should be used fro which use cases.

Other than that thanks for the infos, there is no redundancy. Issue closed.
