### ISSUE TITLE
komLeData - Diskrepanz zwischen Spezifikation und github

### ISSUE THREAD

**Issue by dhufnagel** [gematik/api-vzd#58]
In der "offiziellen" Spezifikation gemSpec_VZD_V1.14.0 ist das komLeData Attribut im JSON Format mit den Attributen "mail" und "version" definiert. 
Hier ist das Attribute als eine CSV-Liste definiert: https://github.com/gematik/api-vzd/blob/main/docs/LDAP_Attribute.adoc#62-komledata .

Eine eindeutige Definition gibt es nicht. In der Spezifikation ist nie von JSON die Rede, nur im Beispiel aufgelistet. In den github docs ist auch nur ein Beispiel, aber keine formale Definition gegeben. 

Wie ist die korrekte Definition des Attributes?

**Comment by spilikin** [comment]
Hallo Dominik,

vielen Dank für den Hinweis. Ich habe bei uns intern die Korrektur der Spezifikation beauftragt - kommt mit dem nächsten Maintenance-Release.

Korrekte Spezifikation ist Koma-separierte auflistung der Adresse und der Version:

Gemäß den Vorgaben antwortet LDAP so:
`komLeData: 1.0,testmail@kim.telematik-test`

**Comment by dhufnagel** [comment]
Vielen Dank. Wo finde ich denn die Spezifikation anhand der die Fachdienste das aktuell umsetzen? Oder klappt das nur durch "Zufall" dass die Fachdienste die korrekte Variante verwenden? Oder tun sie das gar nicht? Oder gibt es da nur interne Absprachen oder Protokollnotizen, an die man sonst nicht herankommt?

**Comment by spilikin** [comment]
In diesem Fall gibt es nur einen zentralen Dienst. Die Spezifikation gilt dem einzigen Hersteller. Für die Nutznießer des VZD publizieren wir die Inhalte hier im github, s. docs

Wenn dabei die KIM-Fachdienste gemeint sind, werden solche Fälle im Staging getestet und ggf. geklärt (RU/TU). Kann schon passieren, dass es Delays oder Menschenfehler bei der Pflege der Dokumentation gibt.

**Comment by dhufnagel** [comment]
Wenn ich jetzt also ein KIM Fachdienst implementiere, dann muss ich das einfach wissen und kann das nicht nachschlagen? Woher bekomme ich so "interne" Änderungen für meine Implementierung?

Laut Aussagen aus gematik-Kreisen ist die auf dem Fachportal veröffentlichte Spezifikation immer führend, da hier die Haftung der gematik greift, bei GitHub wohl nicht. Es kann ja nicht gewollt sein, dass man als Hersteller 5 Dokumentationen vergleichen muss und dann raten muss, welche die korrekte ist?!

**Comment by dhufnagel** [comment]
Ich habe mal kurz geprüft, wann die Änderung stattgefunden hat: Der commit ist von vor 10 Monate (https://github.com/gematik/api-vzd/commit/5473cc0a8047ea3e2d163bebf32d1480d2786165#). Seither gab es mehrere Hotfixe und Maintenance Release. Gibt es gematik-intern auch kein "führendes" Dokument?!

**Comment by spilikin** [comment]
Die Diskrepanz bei komLeData wird in der nächsten Version des gemSpec_VZD korrigiert (ist gerade im Freigabeprozess, 1-2 Wochen ist es im Fachportal). Wenn es noch weitere Auffälligkeiten gibt, würden wir uns um eine Meldung freuen.

Führend sind die Spezifikationen im Fachportal insb. die Produkttypsteckbriefe. Solange die github Inhalte dort nicht verlinkt sind, ja, sind sie nicht normativ. Welche 5 Dokumente muss man als KIM Hersteller lesen? Bis auf unseren Fehler bzgl. komLeData - gibt es weitere Inhalte die unklar sind?

**Comment by dhufnagel** [comment]
Ja, leider gibt es sehr viele Dinge die nicht definiert, unklar oder uneindeutig sind. Diese sind teilweise (da wir vorerst nur ein Clientmodul entwickeln und noch nicht alle AFOs umgesetzt haben) im ServiceDesk für KIM eingetragen aber (teilweise) unbeantwortet. Auch hier gibt es wieder Diskrepanzen zwischen Spec, github und der Umsetzung einzelner Fachdienste (vor Zulassung).

Als KIM-CM Hersteller muss man sowohl die Spezifikation für das Clientmodul, den Fachdienst, den Verzeichnisdienst, Die Kryptospec, github VZD, github KIM-API und BSI TR (und bestimmt noch einige weitere) lesen. Dazu muss man dann RFCs studieren, da nur wage Verweise existieren und sich teilweise dann auch nicht ganz genau an RFCs gehalten wird.

**Comment by dhufnagel** [comment]
Es ist übrigens auch in github noch von "mail"-Attribut und "version"-Attribut die Rede: z.B.
https://github.com/gematik/api-vzd/blob/main/docs/gemILF_Pflege_VZD.adoc#42-kassen%C3%A4rztliche-vereinigungen-smc-b-eintrag
Das ist quasi noch der "Sprech" aus der normativen Spezifikation.

**Comment by spilikin** [comment]
Im Text ist es klar dargestellt wie komLeData kodiert wird. Die Formulierung "mail-Attribut" als Synonym "N-ter Fragment einer Koma-Separated String" kann man in Zukunft sicherlich optimieren. :) 

Über die nicht beantwortete Tickets kann ich leider nichts sagen. Falls die Antworten im Jira Service Desk unzufriedenstellend sind, bitte dort als "Nicht beantwortet" markieren. Ob man glaubt oder nicht wir versuchen jede Frage gut zu beantworten.

**Comment by dhufnagel** [comment]
Ich bezweifle nicht, dass man das versucht. Wir können uns dazu gern auf einem anderen Kanal austauschen, allerdings ist mir nicht ersichtlich, wer sich hinter ihrem Pseudonym verbirgt.
