### ISSUE TITLE
Introduce another EndpointDirectoryPayloadType for non-chatting Messages

### ISSUE THREAD

**Issue by mb010865** [gematik/api-vzd#60]
In the future there will be also procedural HL7 messages through the Matrix communication. It might be good to have a convention for a procedural EndpointPayloadType like "workflow" or "praxis".
I know the CodeSystem can be enhanced easily but everyone can have a separate Endpoint apart from chat messages to send procedural messages already to which any content can be sent which will be consumed by the primary system only.

**Comment by spilikin** [comment]
Hi, 
the idea ist to add the specific PayloadTypes as we go, for each standardized Use-Case. Much like KIM-Dienste:
https://fachportal.gematik.de/toolkit/dienstkennung-kim-kom-le

Still to be able to differentiate between automation and humans ist very good idea. Maybe we can add Several Code Systems to the EndPointPayloadTypes ValueSet, one for Humans (current Code System) and one for Automation (new)

https://simplifier.net/vzd-fhir-directory/endpointpayloadtypevs

Think `TIMAutomationEndpointPayloadTypeCS`. This way all automation codes for TIM will be in one place. What do you think?

**Comment by mb010865** [comment]
Thats a good approach I think and at least have one generic automation PayloadType where to send Future workflow Elements to (Future Konnektor). 
For small installations like our doctors there might be a generic automation type to retrieve workflow messages and we don't have to change the PayloadTypes when a new functionality is introduced. 
We just have to add different Matrix Message Types according to the UseCase.

**Comment by spilikin** [comment]
OK, I will address this with TIM-Team, I think we can provide such "kitchen sink" PayxloadType für _any generic automation_
