### ISSUE TITLE
VZD FederationList JWS X509 certificate is expired

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-vzd#70]
Das X509 Zertifikat welches im JWS Header angehängt ist, ist nicht mehr gültig.
URL: https://fhir-directory-ref.vzd.ti-dienste.de/tim-provider-services/FederationList/federationList.jws

#### JWS Header:
json```
{
  "x5c": [
    "MFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABBi2KzFQ8lK4LS2j2U6zXN2dGl5tnSJyFyCLWw23xu4LacdM8cGcJOvB8gwpj0sBFo6zc1AAiXctHdmG5MapzyY="
  ],
  "typ": "JWT",
  "alg": "ES256"
}
```

#### Zertifikat Details:
- Serial Number: None
- Signature Algorithm: ECDSA with SHA-256
- Issuer: CN=Test CA, O=Test
- Validity:
  - Not Before: March 11, 2021 3:47:32 PM UTC
  - Not After: March 11, 2022 3:47:32 PM UTC
- Subject: CN=Test, O=Test
- Public Key:
  - Algorithm: EC
  - Curve: secp256r1
  - ...

**Comment by gem-uhe** [comment]
Es wurde fälschlicherweise im x5c header der PublicKey statt PublicZertifikat abgelegt. Das sollte gelöst und in TU deployed sein.
