### ISSUE TITLE
VZD federation list JWS: x5c should be a certificate chain

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-vzd#71]
ich kann die JWS Signierung nicht verifizieren, da das gelieferte x5c keine korrekte Chain ist.
aus einer chain kann man den public key extrahieren, was hier leider nicht moeglich ist und demnach auch die Verifizierung verungmoeglicht.

bitte den x5c korrekt generieren.

besten dank

**Comment by gem-uhe** [comment]
Im x5c wird nur das Signierende Zertifikat enthalten sein. Die Chain und das Root-Zertifikat müssen von den bekannten Download-Punkten heruntergeladen werden.

**ROOT-CA Download Punkt** 
PU-Root https://download.tsl.ti-dienste.de/ECC/ROOT-CA/ 
TU-Root https://download-test.tsl.ti-dienste.de/ECC/ROOT-CA/   
RU-Root https://download-ref.tsl.ti-dienste.de/ECC/ROOT-CA/  

**ROOT-CA Download Punkt als JSON-Datei**  
PU-Root https://download.tsl.ti-dienste.de/ECC/ROOT-CA/roots.json 
TU-Root https://download-test.tsl.ti-dienste.de/ECC/ROOT-CA/roots.json  
RU-Root https://download-ref.tsl.ti-dienste.de/ECC/ROOT-CA/roots.json

**Sub-CA Download Punkt** 
PU-Sub https://download.tsl.ti-dienste.de/ECC/SUB-CA/ 
TU-Sub https://download-test.tsl.ti-dienste.de/ECC/SUB-CA/  
RU-Sub https://download-ref.tsl.ti-dienste.de/ECC/SUB-CA/

**Comment by christian-frei** [comment]
Besten Dank für die Antwort. 

Können Sie das bitte in die Spec aufnehmen?

**Comment by gem-uhe** [comment]
Es gibt schon eine Vorabveröffentlichung der Spec Änderungen mit diesen Informationen: https://fachportal.gematik.de/schnelleinstieg/downloadcenter/vorabveroeffentlichungen#c7532
