### ISSUE TITLE
Authentication of a HBA-User via a WebClient and Gematik Authenticator at VZD-Auth is not possible

### ISSUE THREAD

**Issue by awesome-manuel** [gematik/api-vzd#93]
Möglicherweise hängt das damit zusammen, dass dieser Vorgang hier noch nicht beschrieben ist (Kapitel 2.4 ist noch leer):
https://github.com/gematik/api-vzd/blob/61dd4e7115259ecbcacc989962d60e769b32a22f/docs/FHIR_VZD_HOWTO_Authenticate.adoc

### Problem:

![SequenceDiagram.FHIR-Directory.owner](../blob/61dd4e7115259ecbcacc989962d60e769b32a22f/images/diagrams/SequenceDiagram.FHIR-Directory.owner.png?raw=true)

Das Problem liegt zwischen "{client_callback_uri} {auth_code}" und "GET /signin-gematik-idp-dienst with {auth_code}". Die `client_callback_uri` kann tatsächlich nicht frei gewählt werden, der IDP prüft diese. Der Wert bei einer Authentifizierung am Auth-Service ist überlicherweise der `/signin-gematik-idp-dienst` Endpoint des VZD. Im Deeplink kann zumindest gewählt werden, ob dieser am Ende einen [neuen Browser-Tab öffnet oder selbst die Redirect-URI aufruft](https://wiki.gematik.de/display/GAKB/Gematik+Authenticator+SDK+Dokumentation#GematikAuthenticatorSDKDokumentation-NEWAuto-RedirectFunktion(abv4.0.0)). Ein neuer Browser-Tab ist natürlich aus UX-Sicht nicht unbedingt gewünscht, außerdem würde in diesem Tab ja die Redirect-URI geöffnet, also nur ein JSON-Objekt angezeigt. Für die Variante, dass der Authenticator die Redirect-URI selbst aufruft fehlt am VZD jedoch ein passender Endpoint über den der Browser das Ergebnis z.B. per Polling abfragen könnte.

**Comment by spilikin** [comment]
Hi @awesome-manuel 

wir sind an dem Thema dran, Problem erkannt. Kannst du bitte sagen wie eure Komponenten aufgebaut sind. Sind es Nativ-Clients oder Web-Anwendungen? Ist lokale Software oder Webserver der Client ggü. VZD?

**Comment by awesome-manuel** [comment]
Unsere Clients sind Web-Apps (Element-Web). [OpenID](https://openid.net/developers/how-connect-works/) kennt  "OpenID Provider" (Gematik-IDP), "Relying Party oder Client" (VZD) und "User Agent" (Browser). Der Client wäre also das VZD. Das VZD ist beim IDP registriert und hat eine "client_id" und eine "redirect_uri", welche vom IDP geprüft werden.

Wir sehen hier zwei Lösungsmöglichkeiten:
1) [Auto-Redirect im Authenticator](https://wiki.gematik.de/display/GAKB/Gematik+Authenticator+SDK+Dokumentation#GematikAuthenticatorSDKDokumentation-NEWAuto-RedirectFunktion(abv4.0.0)): Hier fehlen im Prinzip die Schritte

     - **Erstelle einen GET-Endpoint für die Redirect-URI:**
Der Server muss einen REST GET-Endpoint zur verfügung stellen welcher der Redirect-URI entspricht. Dieser wird von dem Authenticator aufgerufen wenn der Vorgang abgeschlossen íst.
      _-> Das ist im Prinzip der Endpoint `/signin-gematik-idp-dienst` am VZD_

    - **Erstelle eine sichere Verbindung zwischen dem OIDC-Client und dem Server:**
Um eine sichere Verbindung zwischen dem OIDC-Client und dem Server herzustellen, kann eine Verifikationszeichenfolge (verifier string) über PKCE (Proof Key for Code Exchange) zur Authentifizierung verwendet werden.
      _-> Dieser Punkt fehlt bisher_

2) Standard OIDC, der IDP redet mit dem Authenticator
   Hierfür könnte evtl. der [OIDC CIBA Standard](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html) genutzt werden. D.h. es wird gar kein Deeplink für den Authenticator erstellt, sondern der Authenticator kommuniziert direkt mit dem IDP. Im Prinzip so wie das auch beim Microsoft Authenticator funktioniert. Damit könnte der Authenticator z.B. auch auf einem anderen Gerät (Smartphone) laufen, was die UX weiter erhöht.

**Comment by spilikin** [comment]
Wie du richtig schreibst ist im OIDC Flow der FHR-VZD ein (OAuth2)Client, nicht Element. Wir haben hier mit 4 Parteien zu tun:
* Authenticator
* Element
* VZD
* und IDP-Dienst

Authenticator ist jedoch auf 3 Parteien ausgelegt:
* Authenticator
* Relying Party (=VZD)
* IDP-Dienst

Das macht es etwas schwierig. Im Prinzip ist es ein SSO Szenario, jedoch geht VZD derzeit von "aktiven" Clients aus. Wir suchen gerade nach Lösungen für Web.

Verbindung zum VZD würde dann Server, auf welchen Element läuft, aufbauen oder wollt ihr es direkt auch dem Browser heraus machen?

**Comment by awesome-manuel** [comment]
Die Verbindung zum VZD wird direkt aus dem Browser heraus aufgerufen, also vom User-Agent.

**Comment by spilikin** [comment]
Wie geht ihr mit CORS um? VZD hat derzeit kein CORS
